
version: "3"
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    command: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_DATABASE=postgres"
      - "ALLOW_EMPTY_PASSWORD=yes"
