#@data/values
---
Release:
  Name: release-name
  Service: release-sv
  Namespace: release-ns
Chart:
  Name: chart-name
  AppVersion: chart-appver
  Version: chart-ver

nameOverride: ~
replicaCount: 1
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: false
  hosts:
    - chart-example.local
