version: "2"
services:
  pg-multi-exporter:
    image: pg-multi-exporter
    build: .
    environment:
      - "PG_PASSWORD=postgres"
      - "PG_USERNAME=postgres"
      - "PG_HOST=postgres"
      - "PG_PORT=5432"
      - "PG_SSL_MODE=disable"
  postgres:
    image: test-postgres
    build: images/postgres
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_DATABASE=postgres"
      - "ALLOW_EMPTY_PASSWORD=yes"
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
     - ./images/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    volumes:
     - ./images/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: influxd -config /etc/influxdb/influxdb.conf

  # grafana:
  #   image: grafana/grafana:6.7.2
  #   container_name: grafana
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
  #     - GF_USERS_ALLOW_SIGN_UP=false
  #   restart: unless-stopped
  #   expose:
  #     - 3000
  #   labels:
  #     org.label-schema.group: "monitoring"
volumes:
  postgresql_data:
    driver: local
