version: "3"
services:
  pg-multi-exporter:
    image: pg-multi-exporter
    build: .
    restart: on-failure
    volumes:
      - ./config.yml:/config.yml
      - ./templates:/templates
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USERNAME=postgres"
      - "POSTGRES_DATABASE=postgres"
      - "ALLOW_EMPTY_PASSWORD=yes"
    volumes:
      - ./images/postgres:/docker-entrypoint-initdb.d
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    volumes:
     - ./images/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    command: influxd -config /etc/influxdb/influxdb.conf
  grafana:
    image: grafana/grafana:7.3.4
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./images/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./images/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dasboard.yaml
      - ./images/grafana/dashboards:/etc/dashboards

volumes:
  postgresql_data:
    driver: local
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
