apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: src
  contents:
  - path: lunner
    git:
      url: https://github.com/bodymindarts/lunner.git
      ref: bdd8eb8
  - path: telegraf
    git:
      url: https://github.com/influxdata/telegraf
      ref: v1.16.3
  - path: ytt
    git:
      url: https://github.com/vmware-tanzu/carvel-ytt
      ref: v0.30.0
  - path: azure_metrics_exporter
    git:
      url: https://github.com/webdevops/azure-metrics-exporter
      ref: 20.11.0
  - path: aliyun_exporter
    git:
      url: https://github.com/aylei/aliyun-exporter.git
      ref: v0.3.1
