apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: src
  contents:
  - path: exporter_exporter
    git:
      url: https://github.com/QubitProducts/exporter_exporter
      ref: v0.4.0

