name: pg-multi-exporter
instance_groups:
- name: pg-multi-exporter
  networks:
  - name: default
  stemcell: default
  vm_type: default
  azs: [z1]
  instances: 1
  jobs:
  - name: docker
    release: containers
    properties:
      files:
      - etc/pg-multi-exporter-conf.yml: |
          telegraf:
            debug: false
          influxdb:
            endpoint: "http://((INFLUX_HOST)):((INFLUX_PORT))"
            name_prefix: PREFIX.
          databases:
          - host: ((PG_HOST))
            port: ((PG_PORT))
            username: ((PG_USERNAME))
            password: ((PG_PASSWORD))
      recipe:
        version: '3'
        services:
          pg-multi-exporter:
            volumes:
            - "$PWD/etc/pg-multi-exporter-conf.yml:/config.yml"
            restart: on-failure
            image: starkandwayne/pg-multi-exporter:latest
releases:
- name: containers
  url: https://github.com/jhunt/containers-boshrelease/releases/download/v1.5.1/containers-1.5.1.tgz
  version: 1.5.1

update:
  canaries:          1
  max_in_flight:     1
  serial:            true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest
